"""Services package for gofr-iq.

This package contains all service layer modules:
- document_store: Canonical document storage
- source_registry: Source management
- language_detector: Language detection for documents
- duplicate_detector: Duplicate document detection
- ingest_service: Document ingestion orchestration
- audit_service: Audit logging for all operations
- query_service: Query orchestration
"""

from app.services.audit_service import (
    AuditEntry,
    AuditEventType,
    AuditService,
    create_audit_service,
    log_document_delete,
    log_document_ingest,
    log_document_query,
    log_document_retrieve,
    log_source_create,
    log_source_delete,
    log_source_update,
)
from app.services.document_store import (
    DocumentNotFoundError,
    DocumentStore,
    DocumentStoreError,
)
from app.services.duplicate_detector import (
    CandidateDocument,
    DuplicateDetector,
    DuplicateResult,
    check_duplicate,
    compute_content_hash,
    cosine_similarity,
    normalize_text,
    tokenize,
)
from app.services.embedding_index import (
    Chunk,
    ChunkConfig,
    DeterministicEmbeddingFunction,
    EmbeddingIndex,
    LLMEmbeddingFunction,
    SimilarityResult,
    create_embedding_index,
    create_llm_embedding_function,
)
from app.services.graph_index import (
    GraphIndex,
    GraphNode,
    GraphRelationship,
    NodeLabel,
    RelationType,
    TraversalResult,
    create_graph_index,
)
from app.services.llm_service import (
    ChatCompletionResult,
    ChatMessage,
    EmbeddingResult,
    LLMAPIError,
    LLMConfigurationError,
    LLMRateLimitError,
    LLMService,
    LLMServiceError,
    create_llm_service,
    llm_available,
)
from app.services.ingest_service import (
    IngestError,
    IngestResult,
    IngestService,
    IngestStatus,
    SourceValidationError,
    WordCountError,
    create_ingest_service,
)
from app.services.language_detector import (
    LanguageDetectionError,
    LanguageDetector,
    LanguageResult,
    detect_language,
    detect_language_with_confidence,
)
from app.services.query_service import (
    QueryFilters,
    QueryResponse,
    QueryResult,
    QueryService,
    ScoringWeights,
    create_query_service,
)
from app.services.source_registry import (
    SourceNotFoundError,
    SourceRegistry,
    SourceRegistryError,
)
from app.services.group_service import (
    AdminAccessDeniedError,
    GroupAccessDeniedError,
    GroupService,
    extract_group,
    get_group_service,
    get_permitted_groups,
    get_permitted_groups_from_context,
    get_write_group_from_context,
    init_group_service,
    is_admin,
    require_admin,
)
from app.models.group import PUBLIC_GROUP

__all__ = [
    "AdminAccessDeniedError",
    "AuditEntry",
    "AuditEventType",
    "AuditService",
    "CandidateDocument",
    "ChatCompletionResult",
    "ChatMessage",
    "Chunk",
    "ChunkConfig",
    "DocumentNotFoundError",
    "DocumentStore",
    "DocumentStoreError",
    "DuplicateDetector",
    "DuplicateResult",
    "EmbeddingIndex",
    "EmbeddingResult",
    "GraphIndex",
    "GraphNode",
    "GraphRelationship",
    "GroupAccessDeniedError",
    "GroupService",
    "IngestError",
    "IngestResult",
    "IngestService",
    "IngestStatus",
    "LanguageDetectionError",
    "LanguageDetector",
    "LanguageResult",
    "LLMAPIError",
    "LLMConfigurationError",
    "LLMEmbeddingFunction",
    "LLMRateLimitError",
    "LLMService",
    "LLMServiceError",
    "NodeLabel",
    "PUBLIC_GROUP",
    "QueryFilters",
    "QueryResponse",
    "QueryResult",
    "QueryService",
    "RelationType",
    "ScoringWeights",
    "SimilarityResult",
    "SourceNotFoundError",
    "SourceRegistry",
    "SourceRegistryError",
    "SourceValidationError",
    "TraversalResult",
    "WordCountError",
    "check_duplicate",
    "compute_content_hash",
    "cosine_similarity",
    "create_audit_service",
    "create_embedding_index",
    "create_graph_index",
    "create_ingest_service",
    "create_llm_embedding_function",
    "create_llm_service",
    "create_query_service",
    "detect_language",
    "detect_language_with_confidence",
    "DeterministicEmbeddingFunction",
    "extract_group",
    "get_group_service",
    "get_permitted_groups",
    "get_permitted_groups_from_context",
    "get_write_group_from_context",
    "init_group_service",
    "is_admin",
    "llm_available",
    "log_document_delete",
    "log_document_ingest",
    "log_document_query",
    "log_document_retrieve",
    "log_source_create",
    "log_source_delete",
    "log_source_update",
    "normalize_text",
    "require_admin",
    "tokenize",
]
