#!/bin/bash
# =============================================================================
# Environment Generator
# =============================================================================
# Generates configuration files for Docker and Shell environments.
#
# Usage:
#   ./scripts/generate_envs.sh [--mode prod|test]
#
# Outputs:
#   - config/generated/secrets.env        (prod marker; no secrets emitted)
#   - config/generated/secrets.test.env   (test-only, ephemeral)
# =============================================================================

set -euo pipefail

MODE="prod"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --mode)
            MODE="$2"
            shift 2
            ;;
        *)
            echo "Unknown argument: $1"
            exit 1
            ;;
    esac
done

echo "Generating environments in $MODE mode..."

# Ensure directories exist
mkdir -p "${PROJECT_ROOT}/config/generated"
mkdir -p "${PROJECT_ROOT}/docker"
mkdir -p "${PROJECT_ROOT}/lib/gofr-common/config"

# =============================================================================
# 0. GENERATE PORT CONFIG IF MISSING
# =============================================================================

PORTS_FILE="${PROJECT_ROOT}/lib/gofr-common/config/gofr_ports.env"
if [ ! -f "$PORTS_FILE" ]; then
    echo "  - Generating default port configuration..."
    cat > "$PORTS_FILE" <<'EOF'
# GOFR Port Configuration
# =======================
# Centralized port assignments for all GOFR services and infrastructure.

# GOFR-IQ Service Ports (Production)
export GOFR_IQ_MCP_PORT=8080
export GOFR_IQ_MCPO_PORT=8081
export GOFR_IQ_WEB_PORT=8082

# GOFR-IQ Service Ports (Test - prod + 100)
export GOFR_IQ_MCP_PORT_TEST=8180
export GOFR_IQ_MCPO_PORT_TEST=8181
export GOFR_IQ_WEB_PORT_TEST=8182

# Infrastructure Ports (Production)
export GOFR_VAULT_PORT=8200
export GOFR_CHROMA_PORT=8000
export GOFR_NEO4J_HTTP_PORT=7474
export GOFR_NEO4J_BOLT_PORT=7687

# Infrastructure Ports (Test - prod + 100)
export GOFR_VAULT_PORT_TEST=8201
export GOFR_CHROMA_PORT_TEST=8100
export GOFR_NEO4J_HTTP_PORT_TEST=7574
export GOFR_NEO4J_BOLT_PORT_TEST=7787

# Common Secrets
export GOFR_JWT_SECRET="${GOFR_JWT_SECRET:-change-me-in-production}"
export GOFR_VAULT_DEV_TOKEN="${GOFR_VAULT_DEV_TOKEN:-gofr-dev-root-token}"
EOF
    echo "  - Created: $PORTS_FILE"
fi

# =============================================================================
# 1. SET VAULT CONTEXT
# =============================================================================

if [ "$MODE" == "test" ]; then
    # Test Mode: Use Dev Token and Localhost
    export VAULT_ADDR="http://localhost:8200"
    export VAULT_TOKEN="${GOFR_VAULT_DEV_TOKEN:-gofr-dev-root-token}"
    echo "  - Using Test Vault: $VAULT_ADDR"
else
    # Prod Mode: Expect Vault Env to be set (from secrets/ directory)
    if [ -z "${VAULT_TOKEN:-}" ]; then
        echo "Error: VAULT_TOKEN not set. Load from secrets/vault_root_token first."
        exit 1
    fi
    if [ -z "${VAULT_ADDR:-}" ]; then
        echo "Error: VAULT_ADDR not set. Set explicitly (e.g., http://gofr-vault:8201) before running."
        exit 1
    fi
    echo "  - Using Production info: $VAULT_ADDR"
fi

# =============================================================================
# 2. GENERATE SECRETS FROM VAULT
# =============================================================================

if [ "$MODE" == "test" ]; then
    SECRETS_FILE="${PROJECT_ROOT}/config/generated/secrets.test.env"
else
    SECRETS_FILE="${PROJECT_ROOT}/config/generated/secrets.env"
fi

echo "# Generated by generate_envs.sh for $MODE on $(date)" > "$SECRETS_FILE"

if [ "$MODE" == "test" ]; then
    # Test mode: use dev token and generate ephemeral secrets (test-only file)
    echo "export GOFR_JWT_SECRET=\"${GOFR_JWT_SECRET:-test-secret-$(date +%s)}\"" >> "$SECRETS_FILE"
    echo "export GOFR_ADMIN_TOKEN=\"test-admin-token\"" >> "$SECRETS_FILE"
    echo "export VAULT_ROOT_TOKEN=\"${VAULT_TOKEN}\"" >> "$SECRETS_FILE"
    echo "# WARNING: Test-only secrets; never use in prod" >> "$SECRETS_FILE"
else
    # PROD: Validate secrets exist in Vault but do not emit them to disk
    echo "  - Validating secrets from Vault (no secrets will be written to disk)..."
    JWT_SECRET=$(curl -s -H "X-Vault-Token: ${VAULT_TOKEN}" \
        "${VAULT_ADDR}/v1/secret/data/gofr/config/jwt-signing-secret" \
        | grep -o '"value":"[^"]*"' | cut -d'"' -f4)

    if [ -z "$JWT_SECRET" ]; then
        echo "Error: Could not read JWT secret from Vault. Run bootstrap.py first."
        exit 1
    fi

    OR_KEY=$(curl -s -H "X-Vault-Token: ${VAULT_TOKEN}" \
        "${VAULT_ADDR}/v1/secret/data/gofr/config/api-keys/openrouter" \
        2>/dev/null | grep -o '"value":"[^"]*"' | cut -d'"' -f4 || true)

    echo "# Secrets validated from Vault; not emitted. JWT present: yes; OpenRouter present: ${OR_KEY:+yes}" >> "$SECRETS_FILE"
fi

# =============================================================================
# 3. GENERATE DOCKER ENV
# =============================================================================
# docker/.env generation is reserved for bootstrap.py (Vault-derived only)
echo "  - Created: $SECRETS_FILE"
echo "  - Skipped docker/.env generation (use scripts/bootstrap.py to write Vault-derived .env)"
echo "Done."
