#!/bin/bash
# =============================================================================
# Environment Generator
# =============================================================================
# Generates configuration files for Docker and Shell environments.
#
# Usage:
#   ./scripts/generate_envs.sh [--mode prod|test]
#
# Outputs:
#   - config/generated/secrets.env   (Sourced by scripts)
#   - config/generated/docker.env    (Used by docker-compose)
# =============================================================================

set -euo pipefail

MODE="prod"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --mode)
            MODE="$2"
            shift 2
            ;;
        *)
            echo "Unknown argument: $1"
            exit 1
            ;;
    esac
done

echo "Generating environments in $MODE mode..."

# Ensure directories exist
mkdir -p "${PROJECT_ROOT}/config/generated"
mkdir -p "${PROJECT_ROOT}/docker"
mkdir -p "${PROJECT_ROOT}/lib/gofr-common/config"

# =============================================================================
# 0. GENERATE PORT CONFIG IF MISSING
# =============================================================================

PORTS_FILE="${PROJECT_ROOT}/lib/gofr-common/config/gofr_ports.env"
if [ ! -f "$PORTS_FILE" ]; then
    echo "  - Generating default port configuration..."
    cat > "$PORTS_FILE" <<'EOF'
# GOFR Port Configuration
# =======================
# Centralized port assignments for all GOFR services and infrastructure.

# GOFR-IQ Service Ports (Production)
export GOFR_IQ_MCP_PORT=8080
export GOFR_IQ_MCPO_PORT=8081
export GOFR_IQ_WEB_PORT=8082

# GOFR-IQ Service Ports (Test - prod + 100)
export GOFR_IQ_MCP_PORT_TEST=8180
export GOFR_IQ_MCPO_PORT_TEST=8181
export GOFR_IQ_WEB_PORT_TEST=8182

# Infrastructure Ports (Production)
export GOFR_VAULT_PORT=8200
export GOFR_CHROMA_PORT=8000
export GOFR_NEO4J_HTTP_PORT=7474
export GOFR_NEO4J_BOLT_PORT=7687

# Infrastructure Ports (Test - prod + 100)
export GOFR_VAULT_PORT_TEST=8201
export GOFR_CHROMA_PORT_TEST=8100
export GOFR_NEO4J_HTTP_PORT_TEST=7574
export GOFR_NEO4J_BOLT_PORT_TEST=7787

# Common Secrets
export GOFR_JWT_SECRET="${GOFR_JWT_SECRET:-change-me-in-production}"
export GOFR_VAULT_DEV_TOKEN="${GOFR_VAULT_DEV_TOKEN:-gofr-dev-root-token}"
EOF
    echo "  - Created: $PORTS_FILE"
fi

# =============================================================================
# 1. SET VAULT CONTEXT
# =============================================================================

if [ "$MODE" == "test" ]; then
    # Test Mode: Use Dev Token and Localhost
    export VAULT_ADDR="http://localhost:8200"
    # Use provided Dev token or default
    export VAULT_TOKEN="${GOFR_VAULT_DEV_TOKEN:-gofr-dev-root-token}"
    echo "  - Using Test Vault: $VAULT_ADDR"
else
    # Prod Mode: Expect Vault Env to be set (from .vault-init.env)
    if [ -z "${VAULT_TOKEN:-}" ]; then
        echo "Error: VAULT_TOKEN not set. Source .vault-init.env first."
        exit 1
    fi
    # Default to localhost if not set
    export VAULT_ADDR="${VAULT_ADDR:-http://localhost:8200}"
    echo "  - Using Production info"
fi

# =============================================================================
# 2. GENERATE SECRETS (Using vault_secrets.py logic - simplified here or called)
# =============================================================================
# For now, we stub this or call the python script if it existed.
# Since vault_secrets.py is mentioned in architecture but might not exist in this repo
# fully, we will implement a basic extraction or dummy for now.

SECRETS_FILE="${PROJECT_ROOT}/config/generated/secrets.env"

echo "# Generated by generate_envs.sh for $MODE on $(date)" > "$SECRETS_FILE"

if [ "$MODE" == "test" ]; then
    # In test mode, we might just generate random secrets if Vault isn't reachable
    # OR we try to read from Vault if manage-infra is running.
    # For robustness, if Vault fails, warn but continue with defaults for CI?
    # NO, we want to fail if test infra is not up, as per architecture.
    
    # However, for the very first run, we might need to seed some values.
    echo "export GOFR_JWT_SECRET=\"${GOFR_JWT_SECRET:-test-secret-$(date +%s)}\"" >> "$SECRETS_FILE"
    echo "export GOFR_ADMIN_TOKEN=\"test-admin-token\"" >> "$SECRETS_FILE"
else
    # PROD: We would call vault_secrets.py here.
    # python3 scripts/vault_secrets.py >> "$SECRETS_FILE"
    echo "# PROD SECRETS WOULD BE HERE" >> "$SECRETS_FILE"
fi

# =============================================================================
# 3. GENERATE DOCKER ENV
# =============================================================================
DOCKER_ENV_FILE="${PROJECT_ROOT}/docker/.env"
echo "# Generated by generate_envs.sh for $MODE" > "$DOCKER_ENV_FILE"

# Append base configs
if [ -f "${PROJECT_ROOT}/config/base/infrastructure.env" ]; then
    cat "${PROJECT_ROOT}/config/base/infrastructure.env" >> "$DOCKER_ENV_FILE"
fi
if [ -f "${PROJECT_ROOT}/config/base/services.env" ]; then
    cat "${PROJECT_ROOT}/config/base/services.env" >> "$DOCKER_ENV_FILE"
fi

# Append Secrets
cat "$SECRETS_FILE" >> "$DOCKER_ENV_FILE"

echo "  - Created: $SECRETS_FILE"
echo "  - Created: $DOCKER_ENV_FILE"
echo "Done."
